# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(default=django.utils.timezone.now, verbose_name='日付を入れます')),
            ],
        ),
    ]
